### ISSUE TITLE
Allow starting new task while currently active

### ISSUE THREAD

**Issue by dnaka91** [hardliner66/timetracking#4]
I realized that when a current task is already active, nothing happens when running `tt start ...` again.
It would be nice to just create new task on the fly instead of having to run `tt stop` first.

**Comment by hardliner66** [comment]
Currently there is no real support for tasks. The descriptions can be used to emulate different tasks, but they are intended more like notes. I was thinking about getting real task support in the future, but for that I first need to decide how granular I want the tracking to be. (Customers, Projects, Tasks, Subtasks, etc.)

In the meantime we could just insert the stop event automatically and just hope that this is what the user wants. I think it might be a good idea to add a configuration for that, so that people can use both behaviors, depending on what fits their workflow best.

**Comment by dnaka91** [comment]
True, some people might actually want to not automatically start a new "task". Might be good to give at least a message saying that time is already being tracked right now instead of silently failing.

I can implement that change later if you like.

In regards to the details of granularity for the tracking, maybe [todo.txt](https://github.com/todotxt/todo.txt) can be a guide? The spec describes _contexts_ and _projects_ as ways to categorize things.

**Comment by hardliner66** [comment]
I already started with a base implementation which should be coming soon. I'm gonna look into todo.txt.

**Comment by hardliner66** [comment]
I added preliminary support for what you are asking, which can be enabled through config file. I created an issue to discuss proper task support.
